In [ ]:
def accuracy(output, target, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        res = []
        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size))
        return res



In [ ]:
import torch

# Create some sample data
output = torch.randn(32, )  # Sample output tensor, 5 samples, 3 classes
target = torch.tensor([1, 2, 0, 2, 1])  # Sample target tensor, ground truth labels

# Call the accuracy function
top1, top5 = accuracy(output, target, topk=(1, 5))

print(f"Top-1 Accuracy: {top1.item():.2f}%")
print(f"Top-5 Accuracy: {top5.item():.2f}%")

In [2]:
!pip install torchvision

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip


In [4]:
import torch
print(torch.randn(8, 5))

tensor([[ 0.5560, -1.4274, -0.2668, -0.0637, -1.0900],
        [ 1.4864, -0.0651,  0.1268,  0.4204, -0.2589],
        [ 0.4242, -0.0728,  0.4617, -0.8344,  0.3453],
        [-0.3346,  0.2447,  0.3663, -1.8127, -0.4779],
        [-1.0697, -0.2619, -0.4329, -0.8537, -0.1789],
        [ 1.3182, -1.8663,  0.2477, -0.1045,  0.5833],
        [ 0.0652, -0.2209, -1.3188, -1.5880,  0.2209],
        [ 1.7836,  0.8594,  1.0216, -0.1526,  0.1906]])


In [6]:
#test data loader

import torch
import torchvision
from torchvision import transforms, datasets

def set_loader(data_folder, batch_size): 
    input_shape = (3, 128, 128)

    train_transform = transforms.Compose([
            transforms.Resize(int(input_shape[1] * 156 / 128)),
            transforms.RandomCrop(input_shape[1:]),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5],
                            std=[0.5, 0.5, 0.5])
        ])  

    #assume two crop is not relevant 
    train_dataset = datasets.ImageFolder(
        root=data_folder,
        transform=train_transform
    )

    train_sampler = None
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=batch_size, shuffle=(train_sampler is None),
        pin_memory=True, sampler=train_sampler)

    print("train_loader length: ", len(train_loader))

    return train_loader

In [8]:
train_folder = "./data/test/African/"
train_loader = set_loader(train_folder, 8)

train_loader length:  750


In [21]:
pred = torch.randint(0, 500, (8,3))


In [29]:
#randome int of batch size 8, from 500 classes

topk = (1,5)
batch_size = 8
pred = torch.tensor([[402,  55, 366, 240, 440, 440, 418,  55],
        [416, 108,  75, 366, 192, 309, 402, 108],
        [129, 314, 197, 190, 486, 154, 355,  23],
        [428,  75, 414, 341,  44, 143, 428, 314],
        [ 81, 240, 320, 176, 416, 416, 201, 492]])
print(pred, pred.shape)

for idx, (data, target) in enumerate(train_loader):

    pred = pred.t()
    target = target.view(-1, 1)
    print(target, target.shape)
    target = target.expand_as(pred)
    print(target, target.shape)

    correct = pred.eq(target)
    print(correct)

    res = []
    for k in topk:
        correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
        print(correct_k)
        res.append(correct_k.mul_(100.0 / batch_size))
    
    print(res)
    break 

    # print(idx, data.shape, target.shape)

tensor([[402,  55, 366, 240, 440, 440, 418,  55],
        [416, 108,  75, 366, 192, 309, 402, 108],
        [129, 314, 197, 190, 486, 154, 355,  23],
        [428,  75, 414, 341,  44, 143, 428, 314],
        [ 81, 240, 320, 176, 416, 416, 201, 492]]) torch.Size([5, 8])
tensor([[262],
        [423],
        [177],
        [429],
        [472],
        [214],
        [155],
        [240]]) torch.Size([8, 1])
tensor([[262, 262, 262, 262, 262],
        [423, 423, 423, 423, 423],
        [177, 177, 177, 177, 177],
        [429, 429, 429, 429, 429],
        [472, 472, 472, 472, 472],
        [214, 214, 214, 214, 214],
        [155, 155, 155, 155, 155],
        [240, 240, 240, 240, 240]]) torch.Size([8, 5])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, Fals

In [30]:
res = []
correct = torch.tensor([True, False, False, False, False, False, False, False],
                       [False, False, False, False, False, False, False, False],
                       [True, False, False, False, False, False, False, False])
for k in topk:
    print(correct[:k])
    print(correct[:k].shape)
    print(correct[:k].reshape(-1))
    print(correct[:k].reshape(-1).float().sum(0, keepdim=True))
    print(correct[:k].view(-1))
    correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
    res.append(correct_k.mul_(100.0 / batch_size))
print(res)

tensor([True])
torch.Size([1])
tensor([True])
tensor([1.])
tensor([True])
tensor([ True, False, False, False, False])
torch.Size([5])
tensor([ True, False, False, False, False])
tensor([1.])
tensor([ True, False, False, False, False])
[tensor([12.5000]), tensor([12.5000])]
